### ISSUE TITLE
Monthly Billing Page

### ISSUE THREAD

**Issue by tlpriest** [taskforce-services/taskforce-next-admin#2]
Add this content:

<h1>Steps for Monthly Billing</h1>

1. Review all records in (clockify.me)[https://app.clockify.me/reports/summary]
2. Send invoices to stripe
Start date: [display a calendar, default to the first of last month]
End date: [display a calendar, default to the last day of last month]
[submit]
5. Review invoice records and send via (stripe.com)[https://dashboard.stripe.com/invoices]

When submit is pressed, POST {"from": "YYYY-MM-DD", "to": "YYYY-MM-DD"} to https://eovuxgd9pdeohx.m.pipedream.net?key=pipedream_key which will kick off billing.

**Comment by tlpriest** [comment]
![image](https://user-images.githubusercontent.com/585000/180489845-115416ab-8f25-44d3-a4a7-674ac74691a6.png)

**Comment by AgustinaHer** [comment]
When we merge this, we need to add the new secret URL with the name: NEXT_PUBLIC_PIPEDREAM_INVOICE_URL

**Comment by tlpriest** [comment]
Done
